<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\BookSmith.Core\BookSmith.Core.csproj" />
    <ProjectReference Include="..\BookSmith.Services\BookSmith.Services.csproj" />
    <ProjectReference Include="..\BookSmith.Infrastructure\BookSmith.Infrastructure.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

</Project>
